- name: Configure Rocky Linux System
  hosts: localhost
  become: yes
  tasks:
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "DavidLeahRocky"
        use: "systemd"
      when: ansible_distribution == "Rocky"

    - name: Update dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install ADCLI required packages
      ansible.builtin.dnf:
        name:
          - oddjob
          - oddjob-mkhomedir
          - sssd
          - adcli
          - realmd
        state: latest

    - name: Turn on RealmD
      ansible.builtin.systemd:
        name: realmd
        enabled: true
        state: "started"

    - name: Configure Network Settings
      shell: |
        nmcli connection modify "Wired connection 1" ipv4.method auto
        nmcli connection modify "Wired connection 1" ipv4.dns "192.168.1.1,8.8.8.8"
        nmcli connection modify "Wired connection 1" connection.autoconnect yes
        nmcli connection up "Wired connection 1"
      notify: Restart network

    - name: Check if system is already joined to the realm
      ansible.builtin.command:
        cmd: realm list
      register: realm_list_result
      changed_when: false

    - name: Join network realm if not already joined
      expect:
        command: realm join -U Leah DAVIDLEAH.COM
        responses:
          "Password for Leah@DAVIDLEAH.COM:": "Password123!"
      when: "'davidleah.com' not in realm_list_result.stdout"
      become: true

  handlers:
    - name: Restart network
      command: systemctl restart NetworkManager
