- name: Configure Rocky Linux System
  hosts: localhost
  become: yes
  tasks:
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "DavidLeahRocky"
        use: "systemd"
      when: ansible_distribution == "Rocky"

    - name: Update dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install ADCLI required packages
      ansible.builtin.dnf:
        name:
          - oddjob
          - oddjob-mkhomedir
          - sssd
          - adcli
          - realmd
        state: latest

    - name: Turn on RealmD
      ansible.builtin.systemd:
        name: realmd
        enabled: true
        state: "started"

    - name: Configure Static Network Config Settings
      community.general.nmcli:
        conn_name: ens192
        ifname: ens192
        gw4: 192.168.1.254
        dns4:
          - 192.168.1.1
          - 8.8.8.8
        state: present
        autoconnect: yes
        type: ethernet
      notify: Restart network

    - name: Check if system is already joined to the realm
      ansible.builtin.command:
        cmd: realm list
      register: realm_list_result
      changed_when: false

    - name: Join network realm if not already joined
      ansible.builtin.shell:
        cmd: realm join --user=Leah davidleah.com
      when: "'davidleah.com' not in realm_list_result.stdout"
      become: true

  handlers:
    - name: Restart network
      command: systemctl restart NetworkManager
