---
- name: Assign interfaces
  ansible.builtin.template:
    src: assign_interfaces.expect.j2
    dest: /tmp/assign_interfaces.expect
    mode: 0755

- name: Run interface assignment script
  ansible.builtin.command:
    cmd: /tmp/assign_interfaces.expect
  register: assign_interfaces_result

- name: Configure LAN interface IP
  ansible.builtin.template:
    src: configure_interfaces.expect.j2
    dest: /tmp/configure_interfaces.expect
    mode: 0755

- name: Run LAN interface configuration script
  ansible.builtin.command:
    cmd: /tmp/configure_interfaces.expect
  register: configure_interfaces_result

# this is to change the hostname and domain:
- name: Backup the existing config.xml
  command:
    cmd: cp /cf/conf/config.xml /cf/conf/config.xml.bak
  become: yes

- name: Pull config file
  get_url:
    url: "placeholder.com" #TODO
    dest: "/tmp/config.xml"
    mode: '0644'

- name: Replace the config file
  copy:
    src: "/tmp/config.xml"
    dest: "/cf/conf/config.xml"
    owner: root
    group: wheel
    mode: '0644'
  become: yes

- name: Reload pfSense configuration
  shell: /etc/rc.reload_all
  become: yes
