# Define MAC address mapping for interface assignment
interface_mac_mapping:
  em0: "" # must enter manually before running the ansible
  em1: "" # must enter manually before running the ansible

# LAN interface static IP settings
lan_ip: "192.168.1.254"
lan_netmask: "24"