---
- name: Deployment
  hosts: all
  roles:
    - pfsense-setup
    - rocky
    - windowsserver
    - windowsten
  tags:
    - never
    - initial

- name: Active Directory Setup
  hosts:
    - windows_10
    - windows_server
  roles:
    - active-directory

- name: Network Connectivity and DNS Validation

- name: User Management # Create two users in Active Directory
  hosts:
    - windows_10
    - windows_server
  roles:
  
  # User1: Member of the Domain Users group
  # User2: Member of the Domain Admins group