---
- name: Set Hostname | Windows 10 SETUP
  gather_facts: no
  win_hostname:
    name: "{{ hostname }}"
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Set Static IP | Windows 10 SETUP
  win_network:
    interface_alias: "Ethernet0"
    ipv4_address: "192.168.1.3"
    ipv4_netmask: "255.255.255.0"
    ipv4_gateway: "192.168.1.254"
    dns_servers:
      - "129.21.3.17"
      - "8.8.8.8"