---
- name: Set Hostname | Rocky Linux SETUP
  ansible.builtin.hostname:
    name: "{{ rocky_hostname }}"
  when: ansible_distribution == "Rocky"

- name: Configure Static Network Config Settings | Rocky Linux SETUP
  nmcli:
    conn_name: ens192
    ifname: ens192
    ip4: 192.168.1.2/24
    gw4: 192.168.1.254
    dns4:
      - 129.21.3.17
      - 8.8.8.8
    state: present
    autoconnect: yes
    type: ethernet
  notify: Restart network
  
  handlers:
    - name: Restart network
      command: systemctl restart NetworkManager

# need to join to the domain
# Change the NIC settings on the clients to receive their respective IPv4 network configurations via DHCP (192.168.1.1)
# Verify that the settings are configured for DHCP using the ipconfig /all command