---
- name: Set Hostname | Rocky Linux SETUP
  ansible.builtin.hostname:
    name: "{{ rocky_hostname }}"
  when: ansible_distribution == "Rocky"

- name: Update dnf
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install ADCLI required packages
  ansible.builtin.dnf:
    name:
      - oddjob
      - oddjob-mkhomedir
      - sssd
      - adcli
      - realmd
    state: latest

- name: Turn on RealmD 
  ansible.builtin.systemd:
    name: realmd
    enabled: true
    state: "started"

- name: Configure Static Network Config Settings | Rocky Linux SETUP
  nmcli:
    conn_name: ens192
    ifname: ens192
    gw4: 192.168.1.254
    dns4:
      - 129.21.3.17
      - 8.8.8.8
    state: present
    autoconnect: yes
    type: ethernet
  notify: Restart network
  
  handlers:
    - name: Restart network
      command: systemctl restart NetworkManager

- name: Check if system is already joined to the realm
  ansible.builtin.command:
    cmd: realm list
  register: realm_list_result
  changed_when: false

- name: Join network realm if not already joined
  ansible.builtin.shell:
    cmd: realm join --user=Leah davidleah.com
  when: "'davidleah.com' not in realm_list_result.stdout"
  become: true

# need to join to the domain
# Change the NIC settings on the clients to receive their respective IPv4 network configurations via DHCP (192.168.1.1)
# Verify that the settings are configured for DHCP using the ipconfig /all command